// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sns.proto

#ifndef PROTOBUF_sns_2eproto__INCLUDED
#define PROTOBUF_sns_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)

namespace protobuf_sns_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsListReplyImpl();
void InitDefaultsListReply();
void InitDefaultsRequestImpl();
void InitDefaultsRequest();
void InitDefaultsReplyImpl();
void InitDefaultsReply();
void InitDefaultsRegmessageImpl();
void InitDefaultsRegmessage();
void InitDefaultsMessageImpl();
void InitDefaultsMessage();
inline void InitDefaults() {
  InitDefaultsListReply();
  InitDefaultsRequest();
  InitDefaultsReply();
  InitDefaultsRegmessage();
  InitDefaultsMessage();
}
}  // namespace protobuf_sns_2eproto
namespace csce438 {
class ListReply;
class ListReplyDefaultTypeInternal;
extern ListReplyDefaultTypeInternal _ListReply_default_instance_;
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
class Regmessage;
class RegmessageDefaultTypeInternal;
extern RegmessageDefaultTypeInternal _Regmessage_default_instance_;
class Reply;
class ReplyDefaultTypeInternal;
extern ReplyDefaultTypeInternal _Reply_default_instance_;
class Request;
class RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
}  // namespace csce438
namespace csce438 {

// ===================================================================

class ListReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:csce438.ListReply) */ {
 public:
  ListReply();
  virtual ~ListReply();

  ListReply(const ListReply& from);

  inline ListReply& operator=(const ListReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ListReply(ListReply&& from) noexcept
    : ListReply() {
    *this = ::std::move(from);
  }

  inline ListReply& operator=(ListReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ListReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ListReply* internal_default_instance() {
    return reinterpret_cast<const ListReply*>(
               &_ListReply_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ListReply* other);
  friend void swap(ListReply& a, ListReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ListReply* New() const PROTOBUF_FINAL { return New(NULL); }

  ListReply* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ListReply& from);
  void MergeFrom(const ListReply& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ListReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string all_users = 1;
  int all_users_size() const;
  void clear_all_users();
  static const int kAllUsersFieldNumber = 1;
  const ::std::string& all_users(int index) const;
  ::std::string* mutable_all_users(int index);
  void set_all_users(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_all_users(int index, ::std::string&& value);
  #endif
  void set_all_users(int index, const char* value);
  void set_all_users(int index, const char* value, size_t size);
  ::std::string* add_all_users();
  void add_all_users(const ::std::string& value);
  #if LANG_CXX11
  void add_all_users(::std::string&& value);
  #endif
  void add_all_users(const char* value);
  void add_all_users(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& all_users() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_all_users();

  // repeated string followers = 2;
  int followers_size() const;
  void clear_followers();
  static const int kFollowersFieldNumber = 2;
  const ::std::string& followers(int index) const;
  ::std::string* mutable_followers(int index);
  void set_followers(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_followers(int index, ::std::string&& value);
  #endif
  void set_followers(int index, const char* value);
  void set_followers(int index, const char* value, size_t size);
  ::std::string* add_followers();
  void add_followers(const ::std::string& value);
  #if LANG_CXX11
  void add_followers(::std::string&& value);
  #endif
  void add_followers(const char* value);
  void add_followers(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& followers() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_followers();

  // @@protoc_insertion_point(class_scope:csce438.ListReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> all_users_;
  ::google::protobuf::RepeatedPtrField< ::std::string> followers_;
  mutable int _cached_size_;
  friend struct ::protobuf_sns_2eproto::TableStruct;
  friend void ::protobuf_sns_2eproto::InitDefaultsListReplyImpl();
};
// -------------------------------------------------------------------

class Request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:csce438.Request) */ {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(Request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Request* other);
  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Request* New() const PROTOBUF_FINAL { return New(NULL); }

  Request* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string arguments = 2;
  int arguments_size() const;
  void clear_arguments();
  static const int kArgumentsFieldNumber = 2;
  const ::std::string& arguments(int index) const;
  ::std::string* mutable_arguments(int index);
  void set_arguments(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_arguments(int index, ::std::string&& value);
  #endif
  void set_arguments(int index, const char* value);
  void set_arguments(int index, const char* value, size_t size);
  ::std::string* add_arguments();
  void add_arguments(const ::std::string& value);
  #if LANG_CXX11
  void add_arguments(::std::string&& value);
  #endif
  void add_arguments(const char* value);
  void add_arguments(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& arguments() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_arguments();

  // string username = 1;
  void clear_username();
  static const int kUsernameFieldNumber = 1;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // @@protoc_insertion_point(class_scope:csce438.Request)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> arguments_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  mutable int _cached_size_;
  friend struct ::protobuf_sns_2eproto::TableStruct;
  friend void ::protobuf_sns_2eproto::InitDefaultsRequestImpl();
};
// -------------------------------------------------------------------

class Reply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:csce438.Reply) */ {
 public:
  Reply();
  virtual ~Reply();

  Reply(const Reply& from);

  inline Reply& operator=(const Reply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Reply(Reply&& from) noexcept
    : Reply() {
    *this = ::std::move(from);
  }

  inline Reply& operator=(Reply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Reply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Reply* internal_default_instance() {
    return reinterpret_cast<const Reply*>(
               &_Reply_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Reply* other);
  friend void swap(Reply& a, Reply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Reply* New() const PROTOBUF_FINAL { return New(NULL); }

  Reply* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Reply& from);
  void MergeFrom(const Reply& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Reply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string msg = 1;
  void clear_msg();
  static const int kMsgFieldNumber = 1;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // string hostname = 2;
  void clear_hostname();
  static const int kHostnameFieldNumber = 2;
  const ::std::string& hostname() const;
  void set_hostname(const ::std::string& value);
  #if LANG_CXX11
  void set_hostname(::std::string&& value);
  #endif
  void set_hostname(const char* value);
  void set_hostname(const char* value, size_t size);
  ::std::string* mutable_hostname();
  ::std::string* release_hostname();
  void set_allocated_hostname(::std::string* hostname);

  // string port = 3;
  void clear_port();
  static const int kPortFieldNumber = 3;
  const ::std::string& port() const;
  void set_port(const ::std::string& value);
  #if LANG_CXX11
  void set_port(::std::string&& value);
  #endif
  void set_port(const char* value);
  void set_port(const char* value, size_t size);
  ::std::string* mutable_port();
  ::std::string* release_port();
  void set_allocated_port(::std::string* port);

  // string slavehostname = 4;
  void clear_slavehostname();
  static const int kSlavehostnameFieldNumber = 4;
  const ::std::string& slavehostname() const;
  void set_slavehostname(const ::std::string& value);
  #if LANG_CXX11
  void set_slavehostname(::std::string&& value);
  #endif
  void set_slavehostname(const char* value);
  void set_slavehostname(const char* value, size_t size);
  ::std::string* mutable_slavehostname();
  ::std::string* release_slavehostname();
  void set_allocated_slavehostname(::std::string* slavehostname);

  // string slaveport = 5;
  void clear_slaveport();
  static const int kSlaveportFieldNumber = 5;
  const ::std::string& slaveport() const;
  void set_slaveport(const ::std::string& value);
  #if LANG_CXX11
  void set_slaveport(::std::string&& value);
  #endif
  void set_slaveport(const char* value);
  void set_slaveport(const char* value, size_t size);
  ::std::string* mutable_slaveport();
  ::std::string* release_slaveport();
  void set_allocated_slaveport(::std::string* slaveport);

  // @@protoc_insertion_point(class_scope:csce438.Reply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::internal::ArenaStringPtr hostname_;
  ::google::protobuf::internal::ArenaStringPtr port_;
  ::google::protobuf::internal::ArenaStringPtr slavehostname_;
  ::google::protobuf::internal::ArenaStringPtr slaveport_;
  mutable int _cached_size_;
  friend struct ::protobuf_sns_2eproto::TableStruct;
  friend void ::protobuf_sns_2eproto::InitDefaultsReplyImpl();
};
// -------------------------------------------------------------------

class Regmessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:csce438.Regmessage) */ {
 public:
  Regmessage();
  virtual ~Regmessage();

  Regmessage(const Regmessage& from);

  inline Regmessage& operator=(const Regmessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Regmessage(Regmessage&& from) noexcept
    : Regmessage() {
    *this = ::std::move(from);
  }

  inline Regmessage& operator=(Regmessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Regmessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Regmessage* internal_default_instance() {
    return reinterpret_cast<const Regmessage*>(
               &_Regmessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(Regmessage* other);
  friend void swap(Regmessage& a, Regmessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Regmessage* New() const PROTOBUF_FINAL { return New(NULL); }

  Regmessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Regmessage& from);
  void MergeFrom(const Regmessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Regmessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string hostname = 1;
  void clear_hostname();
  static const int kHostnameFieldNumber = 1;
  const ::std::string& hostname() const;
  void set_hostname(const ::std::string& value);
  #if LANG_CXX11
  void set_hostname(::std::string&& value);
  #endif
  void set_hostname(const char* value);
  void set_hostname(const char* value, size_t size);
  ::std::string* mutable_hostname();
  ::std::string* release_hostname();
  void set_allocated_hostname(::std::string* hostname);

  // string port = 2;
  void clear_port();
  static const int kPortFieldNumber = 2;
  const ::std::string& port() const;
  void set_port(const ::std::string& value);
  #if LANG_CXX11
  void set_port(::std::string&& value);
  #endif
  void set_port(const char* value);
  void set_port(const char* value, size_t size);
  ::std::string* mutable_port();
  ::std::string* release_port();
  void set_allocated_port(::std::string* port);

  // @@protoc_insertion_point(class_scope:csce438.Regmessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr hostname_;
  ::google::protobuf::internal::ArenaStringPtr port_;
  mutable int _cached_size_;
  friend struct ::protobuf_sns_2eproto::TableStruct;
  friend void ::protobuf_sns_2eproto::InitDefaultsRegmessageImpl();
};
// -------------------------------------------------------------------

class Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:csce438.Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(Message&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(Message* other);
  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Message* New() const PROTOBUF_FINAL { return New(NULL); }

  Message* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string username = 1;
  void clear_username();
  static const int kUsernameFieldNumber = 1;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // string msg = 2;
  void clear_msg();
  static const int kMsgFieldNumber = 2;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // .google.protobuf.Timestamp timestamp = 3;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 3;
  const ::google::protobuf::Timestamp& timestamp() const;
  ::google::protobuf::Timestamp* release_timestamp();
  ::google::protobuf::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::google::protobuf::Timestamp* timestamp);

  // @@protoc_insertion_point(class_scope:csce438.Message)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::Timestamp* timestamp_;
  mutable int _cached_size_;
  friend struct ::protobuf_sns_2eproto::TableStruct;
  friend void ::protobuf_sns_2eproto::InitDefaultsMessageImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ListReply

// repeated string all_users = 1;
inline int ListReply::all_users_size() const {
  return all_users_.size();
}
inline void ListReply::clear_all_users() {
  all_users_.Clear();
}
inline const ::std::string& ListReply::all_users(int index) const {
  // @@protoc_insertion_point(field_get:csce438.ListReply.all_users)
  return all_users_.Get(index);
}
inline ::std::string* ListReply::mutable_all_users(int index) {
  // @@protoc_insertion_point(field_mutable:csce438.ListReply.all_users)
  return all_users_.Mutable(index);
}
inline void ListReply::set_all_users(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:csce438.ListReply.all_users)
  all_users_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void ListReply::set_all_users(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:csce438.ListReply.all_users)
  all_users_.Mutable(index)->assign(std::move(value));
}
#endif
inline void ListReply::set_all_users(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  all_users_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:csce438.ListReply.all_users)
}
inline void ListReply::set_all_users(int index, const char* value, size_t size) {
  all_users_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:csce438.ListReply.all_users)
}
inline ::std::string* ListReply::add_all_users() {
  // @@protoc_insertion_point(field_add_mutable:csce438.ListReply.all_users)
  return all_users_.Add();
}
inline void ListReply::add_all_users(const ::std::string& value) {
  all_users_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:csce438.ListReply.all_users)
}
#if LANG_CXX11
inline void ListReply::add_all_users(::std::string&& value) {
  all_users_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:csce438.ListReply.all_users)
}
#endif
inline void ListReply::add_all_users(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  all_users_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:csce438.ListReply.all_users)
}
inline void ListReply::add_all_users(const char* value, size_t size) {
  all_users_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:csce438.ListReply.all_users)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ListReply::all_users() const {
  // @@protoc_insertion_point(field_list:csce438.ListReply.all_users)
  return all_users_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ListReply::mutable_all_users() {
  // @@protoc_insertion_point(field_mutable_list:csce438.ListReply.all_users)
  return &all_users_;
}

// repeated string followers = 2;
inline int ListReply::followers_size() const {
  return followers_.size();
}
inline void ListReply::clear_followers() {
  followers_.Clear();
}
inline const ::std::string& ListReply::followers(int index) const {
  // @@protoc_insertion_point(field_get:csce438.ListReply.followers)
  return followers_.Get(index);
}
inline ::std::string* ListReply::mutable_followers(int index) {
  // @@protoc_insertion_point(field_mutable:csce438.ListReply.followers)
  return followers_.Mutable(index);
}
inline void ListReply::set_followers(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:csce438.ListReply.followers)
  followers_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void ListReply::set_followers(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:csce438.ListReply.followers)
  followers_.Mutable(index)->assign(std::move(value));
}
#endif
inline void ListReply::set_followers(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  followers_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:csce438.ListReply.followers)
}
inline void ListReply::set_followers(int index, const char* value, size_t size) {
  followers_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:csce438.ListReply.followers)
}
inline ::std::string* ListReply::add_followers() {
  // @@protoc_insertion_point(field_add_mutable:csce438.ListReply.followers)
  return followers_.Add();
}
inline void ListReply::add_followers(const ::std::string& value) {
  followers_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:csce438.ListReply.followers)
}
#if LANG_CXX11
inline void ListReply::add_followers(::std::string&& value) {
  followers_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:csce438.ListReply.followers)
}
#endif
inline void ListReply::add_followers(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  followers_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:csce438.ListReply.followers)
}
inline void ListReply::add_followers(const char* value, size_t size) {
  followers_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:csce438.ListReply.followers)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ListReply::followers() const {
  // @@protoc_insertion_point(field_list:csce438.ListReply.followers)
  return followers_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ListReply::mutable_followers() {
  // @@protoc_insertion_point(field_mutable_list:csce438.ListReply.followers)
  return &followers_;
}

// -------------------------------------------------------------------

// Request

// string username = 1;
inline void Request::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Request::username() const {
  // @@protoc_insertion_point(field_get:csce438.Request.username)
  return username_.GetNoArena();
}
inline void Request::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:csce438.Request.username)
}
#if LANG_CXX11
inline void Request::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:csce438.Request.username)
}
#endif
inline void Request::set_username(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:csce438.Request.username)
}
inline void Request::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:csce438.Request.username)
}
inline ::std::string* Request::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:csce438.Request.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request::release_username() {
  // @@protoc_insertion_point(field_release:csce438.Request.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:csce438.Request.username)
}

// repeated string arguments = 2;
inline int Request::arguments_size() const {
  return arguments_.size();
}
inline void Request::clear_arguments() {
  arguments_.Clear();
}
inline const ::std::string& Request::arguments(int index) const {
  // @@protoc_insertion_point(field_get:csce438.Request.arguments)
  return arguments_.Get(index);
}
inline ::std::string* Request::mutable_arguments(int index) {
  // @@protoc_insertion_point(field_mutable:csce438.Request.arguments)
  return arguments_.Mutable(index);
}
inline void Request::set_arguments(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:csce438.Request.arguments)
  arguments_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void Request::set_arguments(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:csce438.Request.arguments)
  arguments_.Mutable(index)->assign(std::move(value));
}
#endif
inline void Request::set_arguments(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  arguments_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:csce438.Request.arguments)
}
inline void Request::set_arguments(int index, const char* value, size_t size) {
  arguments_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:csce438.Request.arguments)
}
inline ::std::string* Request::add_arguments() {
  // @@protoc_insertion_point(field_add_mutable:csce438.Request.arguments)
  return arguments_.Add();
}
inline void Request::add_arguments(const ::std::string& value) {
  arguments_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:csce438.Request.arguments)
}
#if LANG_CXX11
inline void Request::add_arguments(::std::string&& value) {
  arguments_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:csce438.Request.arguments)
}
#endif
inline void Request::add_arguments(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  arguments_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:csce438.Request.arguments)
}
inline void Request::add_arguments(const char* value, size_t size) {
  arguments_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:csce438.Request.arguments)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Request::arguments() const {
  // @@protoc_insertion_point(field_list:csce438.Request.arguments)
  return arguments_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Request::mutable_arguments() {
  // @@protoc_insertion_point(field_mutable_list:csce438.Request.arguments)
  return &arguments_;
}

// -------------------------------------------------------------------

// Reply

// string msg = 1;
inline void Reply::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Reply::msg() const {
  // @@protoc_insertion_point(field_get:csce438.Reply.msg)
  return msg_.GetNoArena();
}
inline void Reply::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:csce438.Reply.msg)
}
#if LANG_CXX11
inline void Reply::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:csce438.Reply.msg)
}
#endif
inline void Reply::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:csce438.Reply.msg)
}
inline void Reply::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:csce438.Reply.msg)
}
inline ::std::string* Reply::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:csce438.Reply.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Reply::release_msg() {
  // @@protoc_insertion_point(field_release:csce438.Reply.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Reply::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:csce438.Reply.msg)
}

// string hostname = 2;
inline void Reply::clear_hostname() {
  hostname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Reply::hostname() const {
  // @@protoc_insertion_point(field_get:csce438.Reply.hostname)
  return hostname_.GetNoArena();
}
inline void Reply::set_hostname(const ::std::string& value) {
  
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:csce438.Reply.hostname)
}
#if LANG_CXX11
inline void Reply::set_hostname(::std::string&& value) {
  
  hostname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:csce438.Reply.hostname)
}
#endif
inline void Reply::set_hostname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:csce438.Reply.hostname)
}
inline void Reply::set_hostname(const char* value, size_t size) {
  
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:csce438.Reply.hostname)
}
inline ::std::string* Reply::mutable_hostname() {
  
  // @@protoc_insertion_point(field_mutable:csce438.Reply.hostname)
  return hostname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Reply::release_hostname() {
  // @@protoc_insertion_point(field_release:csce438.Reply.hostname)
  
  return hostname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Reply::set_allocated_hostname(::std::string* hostname) {
  if (hostname != NULL) {
    
  } else {
    
  }
  hostname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hostname);
  // @@protoc_insertion_point(field_set_allocated:csce438.Reply.hostname)
}

// string port = 3;
inline void Reply::clear_port() {
  port_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Reply::port() const {
  // @@protoc_insertion_point(field_get:csce438.Reply.port)
  return port_.GetNoArena();
}
inline void Reply::set_port(const ::std::string& value) {
  
  port_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:csce438.Reply.port)
}
#if LANG_CXX11
inline void Reply::set_port(::std::string&& value) {
  
  port_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:csce438.Reply.port)
}
#endif
inline void Reply::set_port(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  port_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:csce438.Reply.port)
}
inline void Reply::set_port(const char* value, size_t size) {
  
  port_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:csce438.Reply.port)
}
inline ::std::string* Reply::mutable_port() {
  
  // @@protoc_insertion_point(field_mutable:csce438.Reply.port)
  return port_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Reply::release_port() {
  // @@protoc_insertion_point(field_release:csce438.Reply.port)
  
  return port_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Reply::set_allocated_port(::std::string* port) {
  if (port != NULL) {
    
  } else {
    
  }
  port_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), port);
  // @@protoc_insertion_point(field_set_allocated:csce438.Reply.port)
}

// string slavehostname = 4;
inline void Reply::clear_slavehostname() {
  slavehostname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Reply::slavehostname() const {
  // @@protoc_insertion_point(field_get:csce438.Reply.slavehostname)
  return slavehostname_.GetNoArena();
}
inline void Reply::set_slavehostname(const ::std::string& value) {
  
  slavehostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:csce438.Reply.slavehostname)
}
#if LANG_CXX11
inline void Reply::set_slavehostname(::std::string&& value) {
  
  slavehostname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:csce438.Reply.slavehostname)
}
#endif
inline void Reply::set_slavehostname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  slavehostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:csce438.Reply.slavehostname)
}
inline void Reply::set_slavehostname(const char* value, size_t size) {
  
  slavehostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:csce438.Reply.slavehostname)
}
inline ::std::string* Reply::mutable_slavehostname() {
  
  // @@protoc_insertion_point(field_mutable:csce438.Reply.slavehostname)
  return slavehostname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Reply::release_slavehostname() {
  // @@protoc_insertion_point(field_release:csce438.Reply.slavehostname)
  
  return slavehostname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Reply::set_allocated_slavehostname(::std::string* slavehostname) {
  if (slavehostname != NULL) {
    
  } else {
    
  }
  slavehostname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), slavehostname);
  // @@protoc_insertion_point(field_set_allocated:csce438.Reply.slavehostname)
}

// string slaveport = 5;
inline void Reply::clear_slaveport() {
  slaveport_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Reply::slaveport() const {
  // @@protoc_insertion_point(field_get:csce438.Reply.slaveport)
  return slaveport_.GetNoArena();
}
inline void Reply::set_slaveport(const ::std::string& value) {
  
  slaveport_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:csce438.Reply.slaveport)
}
#if LANG_CXX11
inline void Reply::set_slaveport(::std::string&& value) {
  
  slaveport_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:csce438.Reply.slaveport)
}
#endif
inline void Reply::set_slaveport(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  slaveport_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:csce438.Reply.slaveport)
}
inline void Reply::set_slaveport(const char* value, size_t size) {
  
  slaveport_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:csce438.Reply.slaveport)
}
inline ::std::string* Reply::mutable_slaveport() {
  
  // @@protoc_insertion_point(field_mutable:csce438.Reply.slaveport)
  return slaveport_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Reply::release_slaveport() {
  // @@protoc_insertion_point(field_release:csce438.Reply.slaveport)
  
  return slaveport_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Reply::set_allocated_slaveport(::std::string* slaveport) {
  if (slaveport != NULL) {
    
  } else {
    
  }
  slaveport_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), slaveport);
  // @@protoc_insertion_point(field_set_allocated:csce438.Reply.slaveport)
}

// -------------------------------------------------------------------

// Regmessage

// string hostname = 1;
inline void Regmessage::clear_hostname() {
  hostname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Regmessage::hostname() const {
  // @@protoc_insertion_point(field_get:csce438.Regmessage.hostname)
  return hostname_.GetNoArena();
}
inline void Regmessage::set_hostname(const ::std::string& value) {
  
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:csce438.Regmessage.hostname)
}
#if LANG_CXX11
inline void Regmessage::set_hostname(::std::string&& value) {
  
  hostname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:csce438.Regmessage.hostname)
}
#endif
inline void Regmessage::set_hostname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:csce438.Regmessage.hostname)
}
inline void Regmessage::set_hostname(const char* value, size_t size) {
  
  hostname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:csce438.Regmessage.hostname)
}
inline ::std::string* Regmessage::mutable_hostname() {
  
  // @@protoc_insertion_point(field_mutable:csce438.Regmessage.hostname)
  return hostname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Regmessage::release_hostname() {
  // @@protoc_insertion_point(field_release:csce438.Regmessage.hostname)
  
  return hostname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Regmessage::set_allocated_hostname(::std::string* hostname) {
  if (hostname != NULL) {
    
  } else {
    
  }
  hostname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hostname);
  // @@protoc_insertion_point(field_set_allocated:csce438.Regmessage.hostname)
}

// string port = 2;
inline void Regmessage::clear_port() {
  port_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Regmessage::port() const {
  // @@protoc_insertion_point(field_get:csce438.Regmessage.port)
  return port_.GetNoArena();
}
inline void Regmessage::set_port(const ::std::string& value) {
  
  port_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:csce438.Regmessage.port)
}
#if LANG_CXX11
inline void Regmessage::set_port(::std::string&& value) {
  
  port_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:csce438.Regmessage.port)
}
#endif
inline void Regmessage::set_port(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  port_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:csce438.Regmessage.port)
}
inline void Regmessage::set_port(const char* value, size_t size) {
  
  port_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:csce438.Regmessage.port)
}
inline ::std::string* Regmessage::mutable_port() {
  
  // @@protoc_insertion_point(field_mutable:csce438.Regmessage.port)
  return port_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Regmessage::release_port() {
  // @@protoc_insertion_point(field_release:csce438.Regmessage.port)
  
  return port_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Regmessage::set_allocated_port(::std::string* port) {
  if (port != NULL) {
    
  } else {
    
  }
  port_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), port);
  // @@protoc_insertion_point(field_set_allocated:csce438.Regmessage.port)
}

// -------------------------------------------------------------------

// Message

// string username = 1;
inline void Message::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Message::username() const {
  // @@protoc_insertion_point(field_get:csce438.Message.username)
  return username_.GetNoArena();
}
inline void Message::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:csce438.Message.username)
}
#if LANG_CXX11
inline void Message::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:csce438.Message.username)
}
#endif
inline void Message::set_username(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:csce438.Message.username)
}
inline void Message::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:csce438.Message.username)
}
inline ::std::string* Message::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:csce438.Message.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message::release_username() {
  // @@protoc_insertion_point(field_release:csce438.Message.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:csce438.Message.username)
}

// string msg = 2;
inline void Message::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Message::msg() const {
  // @@protoc_insertion_point(field_get:csce438.Message.msg)
  return msg_.GetNoArena();
}
inline void Message::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:csce438.Message.msg)
}
#if LANG_CXX11
inline void Message::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:csce438.Message.msg)
}
#endif
inline void Message::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:csce438.Message.msg)
}
inline void Message::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:csce438.Message.msg)
}
inline ::std::string* Message::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:csce438.Message.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message::release_msg() {
  // @@protoc_insertion_point(field_release:csce438.Message.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:csce438.Message.msg)
}

// .google.protobuf.Timestamp timestamp = 3;
inline bool Message::has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != NULL;
}
inline const ::google::protobuf::Timestamp& Message::timestamp() const {
  const ::google::protobuf::Timestamp* p = timestamp_;
  // @@protoc_insertion_point(field_get:csce438.Message.timestamp)
  return p != NULL ? *p : *reinterpret_cast<const ::google::protobuf::Timestamp*>(
      &::google::protobuf::_Timestamp_default_instance_);
}
inline ::google::protobuf::Timestamp* Message::release_timestamp() {
  // @@protoc_insertion_point(field_release:csce438.Message.timestamp)
  
  ::google::protobuf::Timestamp* temp = timestamp_;
  timestamp_ = NULL;
  return temp;
}
inline ::google::protobuf::Timestamp* Message::mutable_timestamp() {
  
  if (timestamp_ == NULL) {
    timestamp_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:csce438.Message.timestamp)
  return timestamp_;
}
inline void Message::set_allocated_timestamp(::google::protobuf::Timestamp* timestamp) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast< ::google::protobuf::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:csce438.Message.timestamp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace csce438

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_sns_2eproto__INCLUDED
